
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace GenerateIranianNationalCodes_ML_Detection
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Enter the NationalCode : ");
            var  input = Console.ReadLine();
            
            // Create single instance of sample data from first line of dataset for model input
            MLncodeModel.ModelInput sampleData = new()
            {
                Ncode = Convert.ToInt64(input),
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLncodeModel.Predict(sampleData);
            Console.WriteLine("Using model to make single prediction -- Comparing actual City with predicted City from sample data...\n\n");


            Console.WriteLine($"\nPredicted City: {predictionResult.Prediction}\n\n");
            Console.WriteLine($"\nPredicted Percentage: {predictionResult.Score[0]}  {predictionResult.Score[1]} \n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
